name: GolangCI
on: [push]
jobs:
  test-units:
    name: Go test on ${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.11', '1.12', '1.13' ]
    steps:
      - uses: actions/checkout@master
      - name: Setup go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go get -v ./...
      - run: go test -v .

  test-lint:
    name: Lint go package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.19.1
      - run: $(go env GOPATH)/bin/golangci-lint run --enable-all --disable gochecknoglobals,gochecknoinits
